# Artificial Neutral Network Customer Churn Prediction

#Installing Theano, Tensorflow, Keras

In [8]:
import keras

Using TensorFlow backend.


In [9]:
# The code was removed by DSX for sharing.

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [10]:
import numpy as np

In [69]:
X=df_data_1.iloc[:,3:13].values

In [70]:
y=df_data_1.iloc[:,13].values

#Encoding Categorical data

In [71]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])


In [72]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ..., 
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [73]:
#Create dummy variables
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [22]:
X


array([[  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   1.00000000e+00,   1.01348880e+05],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   1.00000000e+00,   1.12542580e+05],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   0.00000000e+00,   1.13931570e+05],
       ..., 
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   1.00000000e+00,   4.20855800e+04],
       [  0.00000000e+00,   1.00000000e+00,   1.00000000e+00, ...,
          1.00000000e+00,   0.00000000e+00,   9.28885200e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          1.00000000e+00,   0.00000000e+00,   3.81907800e+04]])

In [74]:
#Splitting training and test dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


In [75]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [76]:
from keras.models import Sequential
from keras.layers import Dense

In [77]:
#initializing classfier
classifier =Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))


In [78]:
X.shape

(10000, 11)

In [79]:
X_train.shape

(8000, 11)

In [80]:
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))


/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", input_dim=11, units=6, activation="relu")`
  if __name__ == '__main__':


In [41]:
import pip

In [ ]:
!pip install --upgrade keras

In [81]:
#Add second hidden layer
from ipykernel import kernelapp as app

classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))


/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:4: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=6, activation="relu")`


In [86]:
#Add Output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))



/opt/conda/envs/DSX-Python35/lib/python3.5/site-packages/ipykernel/__main__.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=1, activation="sigmoid")`
  from ipykernel import kernelapp as app


In [87]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [88]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)


Epoch 1/100
8000/8000 [==============================] - 6s 746us/step - loss: 0.5076 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 6s 735us/step - loss: 0.4547 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 6s 726us/step - loss: 0.4437 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 6s 714us/step - loss: 0.4354 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 6s 724us/step - loss: 0.4288 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 6s 749us/step - loss: 0.4242 - acc: 0.7960
Epoch 7/100
8000/8000 [==============================] - 6s 726us/step - loss: 0.4208 - acc: 0.7960
Epoch 8/100
8000/8000 [==============================] - 6s 713us/step - loss: 0.4176 - acc: 0.8004
Epoch 9/100
8000/8000 [==============================] - 6s 713us/step - loss: 0.4157 - acc: 0.8296
Epoch 10/100
8000/8000 [==============================] - 6s 726us/step - loss: 0.4140 - acc: 0.8312

In [95]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [96]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [97]:
cm

array([[1554,   41],
       [ 269,  136]])

In [92]:
y_pred

array([[False],
       [False],
       [False],
       ..., 
       [False],
       [False],
       [False]], dtype=bool)

In [93]:
y_pred = classifier.predict(X_test)


In [94]:
y_pred

array([[ 0.16240008],
       [ 0.33329418],
       [ 0.14915329],
       ..., 
       [ 0.10266108],
       [ 0.15848713],
       [ 0.14016064]], dtype=float32)

In [98]:
accuracy=(1554+136)/2000

In [99]:
accuracy

0.845